version: '2'
services:
  web:
    container_name: tomcat
    image: tomcat-docker
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./ssl:/usr/local/tomcat/ssl
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs:/usr/local/tomcat/logs  
