version: '2'
services:
  web:
    container_name: tomcat
    image: tomcat:9.0.5-jre8
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./ssl:/usr/local/tomcat/ssl
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./webapps:/usr/local/tomcat/webapps/sample.war
      - ./logs:/usr/local/tomcat/logs  
